### ISSUE TITLE
Add add_child, remove_child function for FlexboxLayout

### ISSUE THREAD

**Issue by ivanceras** [gabdube/native-windows-gui#72]
This allows a flexible dynamic UI. I think adding the children to the `FlexboxLayout` is merely taking out the children `Control` of the child `FlexboxLayout` and add it on the parent FlexboxLayout, I'm not sure though. I'm also surprise that the underlying windows UI doesn't actually have a native layout support. So, the higher level UI frameworks will have to calculate them.

Take note also, that the stretch layout computation is calculating the location of each children relative to the parent container. So, to put the child component in their absolute position, I have to [add the parent location to each of the child location](https://github.com/ivanceras/titik/blob/master/src/control/layout.rs#L46) after the layout computation.

**Comment by gabdube** [comment]
Implemented in FlexBoxLayout. Also added a `has_child` to check if a control is in a layout. Will close when it will be implemented in GridLayout too.

**Comment by gabdube** [comment]
Done

**Comment by ivanceras** [comment]
How do I nest FlexboxLayout as a child of another FlexboxLayout?

**Comment by gabdube** [comment]
Using Frames. Add a frame children to the top layout and set the new layout on the frame. That's a workaround until NWG supports adding children directly to layouts

Window 
 -- Layout
   -- Frame
     -- Layout2

**Comment by ivanceras** [comment]
@gabdube , I still can't figure out how to nest flexbox layout. I tried to wrap flexbox layout in a frame, but the frame can not have the flexbox layout as a child. It would be nice if there is a simple example on how to do this.

**Comment by gabdube** [comment]
The treeview example has a nested layout example. https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/treeview_d.rs

You can see `control_layout` is applied to `control_frame`. It uses the derive macro, but it maps directly to the builder you'd use without it.

**Comment by fenhl** [comment]
Turns out you need to set the flexbox's `flex_direction` and the checkbox's style, otherwise nothing will be displayed: <https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/flexbox_dynamic_d.rs>
